spring.application.name=resortHUB

# Port chạy server
server.port=3000

# Cấu hình kết nối cơ sở dữ liệu
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=resortHUBData;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
